server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: preapply
          uri: http://localhost:8081
          predicates:
            - Path=/preApplicationAS/** 
        - id: incomecheck
          uri: http://localhost:8082
          predicates:
            - Path=/incomeVerificationResultAS/** 
        - id: accountopen
          uri: http://localhost:8083
          predicates:
            - Path=/accountAS/** 
        - id: dashboard
          uri: http://localhost:8084
          predicates:
            - Path= 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: preapply
          uri: http://preapply:8080
          predicates:
            - Path=/preApplicationAS/** 
        - id: incomecheck
          uri: http://incomecheck:8080
          predicates:
            - Path=/incomeVerificationResultAS/** 
        - id: accountopen
          uri: http://accountopen:8080
          predicates:
            - Path=/accountAS/** 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path= 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
