apiVersion: apps/v1
kind: Deployment
metadata:
  name: preapply
  labels:
    app: preapply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preapply
  template:
    metadata:
      labels:
        app: preapply
    spec:
      containers:
        - name: preapply
          image: username/preapply:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5