---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: preapply
  labels:
    app: preapply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preapply
  template:
    metadata:
      labels:
        app: preapply
    spec:
      containers:
        - name: preapply
          image: username/preapply:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: incomecheck
  labels:
    app: incomecheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incomecheck
  template:
    metadata:
      labels:
        app: incomecheck
    spec:
      containers:
        - name: incomecheck
          image: username/incomecheck:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountopen
  labels:
    app: accountopen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountopen
  template:
    metadata:
      labels:
        app: accountopen
    spec:
      containers:
        - name: accountopen
          image: username/accountopen:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  labels:
    app: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: username/dashboard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: preapply
  labels:
    app: preapply
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: preapply


---


apiVersion: v1
kind: Service
metadata:
  name: incomecheck
  labels:
    app: incomecheck
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: incomecheck


---


apiVersion: v1
kind: Service
metadata:
  name: accountopen
  labels:
    app: accountopen
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: accountopen


---


apiVersion: v1
kind: Service
metadata:
  name: dashboard
  labels:
    app: dashboard
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: dashboard

