apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountopen
  labels:
    app: accountopen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountopen
  template:
    metadata:
      labels:
        app: accountopen
    spec:
      containers:
        - name: accountopen
          image: username/accountopen:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5