apiVersion: apps/v1
kind: Deployment
metadata:
  name: incomecheck
  labels:
    app: incomecheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incomecheck
  template:
    metadata:
      labels:
        app: incomecheck
    spec:
      containers:
        - name: incomecheck
          image: username/incomecheck:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5